DROP TABLE IF EXISTS `combats_archives`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `combats_archives` (
  `idArchive` int(10) unsigned NOT NULL default '0',
  `idAttaquant` mediumint(7) unsigned NOT NULL default '0',
  `idDefenseur` mediumint(7) unsigned NOT NULL default '0',
  `idVainqueur` mediumint(7) unsigned NOT NULL default '0',
  `texte` mediumtext NOT NULL,
  `discussion` text NOT NULL,
  `debutGuerre` int(10) unsigned NOT NULL default '0',
  `finGuerre` int(10) unsigned NOT NULL default '0',
  `nombreToursJoues` mediumint(5) unsigned NOT NULL default '0',
  `fuite` enum('0','1') NOT NULL default '0',
  `pillage` enum('0','1') NOT NULL default '0',
  `nombreRaAttaquant` tinyint(3) unsigned NOT NULL default '0',
  `nombreRaDefenseur` tinyint(3) unsigned NOT NULL default '0',
  `xpGagneeAtt` int(8) NOT NULL default '0',
  `xpGagneeDef` int(8) NOT NULL default '0',
  `xpSuppHumainAtt` mediumint(5) NOT NULL default '0',
  `xpSuppHumainDef` mediumint(5) NOT NULL default '0',
  `xpSuppFioleAtt` mediumint(7) unsigned NOT NULL default '0',
  `xpSuppFioleDef` mediumint(7) unsigned NOT NULL default '0',
  `etatLectureAtt` enum('0','1') NOT NULL default '0',
  `etatLectureDef` enum('0','1') NOT NULL default '0',
  `etatSuppressionAtt` enum('0','1') NOT NULL default '0',
  `etatSuppressionDef` enum('0','1') NOT NULL default '0',
  `woodAtt` int(10) unsigned NOT NULL default '0',
  `foodAtt` int(10) unsigned NOT NULL default '0',
  `goldAtt` int(10) unsigned NOT NULL default '0',
  `rockAtt` int(10) unsigned NOT NULL default '0',
  `madrensAtt` int(10) unsigned NOT NULL default '0',
  `foodDef` int(10) unsigned NOT NULL default '0',
  `woodDef` int(10) unsigned NOT NULL default '0',
  `goldDef` int(10) unsigned NOT NULL default '0',
  `rockDef` int(10) unsigned NOT NULL default '0',
  `madrensDef` int(10) unsigned NOT NULL default '0',
  `foodPerdueDef` int(10) unsigned NOT NULL default '0',
  `woodPerduDef` int(10) unsigned NOT NULL default '0',
  `goldPerduDef` int(10) unsigned NOT NULL default '0',
  `rockPerdueDef` int(10) unsigned NOT NULL default '0',
  `madrensPerdusDef` int(10) unsigned NOT NULL default '0',
  `capaciteAtt` int(10) unsigned NOT NULL default '0',
  `peonsTues` int(7) unsigned NOT NULL default '0',
  `moralAtt` int(11) NOT NULL default '0',
  `moralDef` int(11) NOT NULL default '0',
  `techUniqueNecAtt` text NOT NULL,
  `techUniqueNecDef` text NOT NULL,
  `techniqueAttUtilisee` enum('0','1') NOT NULL default '0',
  `techniqueDefUtilisee` enum('0','1') NOT NULL default '0',
  PRIMARY KEY  (`idArchive`),
  KEY `idAttaquant` (`idAttaquant`),
  KEY `idDefenseur` (`idDefenseur`),
  KEY `idVainqueur` (`idVainqueur`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Historique des combats';
SET character_set_client = @saved_cs_client;
